## import cv libraries

In [1]:
pip install opencv-python

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 26.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


## check it's version

In [1]:
import cv2
print(cv2.__version__)

4.13.0


## Read an image

In [2]:
import cv2
img = cv2.imread('UCA-7.jpg')
print(img)

[[[112 131 174]
  [111 130 173]
  [111 130 173]
  ...
  [ 48  62  84]
  [ 49  63  85]
  [ 50  64  86]]

 [[110 129 172]
  [111 130 173]
  [111 130 173]
  ...
  [ 48  62  84]
  [ 50  64  86]
  [ 50  64  86]]

 [[110 129 172]
  [111 130 173]
  [110 129 172]
  ...
  [ 46  61  80]
  [ 47  62  81]
  [ 48  63  82]]

 ...

 [[ 78 104 141]
  [ 78 104 141]
  [ 77 103 140]
  ...
  [ 13  39  79]
  [ 12  38  78]
  [ 12  38  78]]

 [[ 80 103 141]
  [ 79 102 140]
  [ 79 102 140]
  ...
  [ 12  37  79]
  [ 12  37  79]
  [ 11  36  78]]

 [[ 79 102 140]
  [ 78 101 139]
  [ 78 101 139]
  ...
  [ 13  38  80]
  [ 13  38  80]
  [ 13  38  80]]]


In [4]:
imgs = cv2.imread('UCA-7.jpg')
print(imgs)

[[[112 131 174]
  [111 130 173]
  [111 130 173]
  ...
  [ 48  62  84]
  [ 49  63  85]
  [ 50  64  86]]

 [[110 129 172]
  [111 130 173]
  [111 130 173]
  ...
  [ 48  62  84]
  [ 50  64  86]
  [ 50  64  86]]

 [[110 129 172]
  [111 130 173]
  [110 129 172]
  ...
  [ 46  61  80]
  [ 47  62  81]
  [ 48  63  82]]

 ...

 [[ 78 104 141]
  [ 78 104 141]
  [ 77 103 140]
  ...
  [ 13  39  79]
  [ 12  38  78]
  [ 12  38  78]]

 [[ 80 103 141]
  [ 79 102 140]
  [ 79 102 140]
  ...
  [ 12  37  79]
  [ 12  37  79]
  [ 11  36  78]]

 [[ 79 102 140]
  [ 78 101 139]
  [ 78 101 139]
  ...
  [ 13  38  80]
  [ 13  38  80]
  [ 13  38  80]]]


In [5]:
import cv2

# Read the image file
imgs = cv2.imread('UCA-7.jpg')  # ✅ CORRECT - reads the image

# Check if image was loaded successfully
if imgs is None:
    print("Error: Could not read the image file. Check if 'UCA-7.jpg' exists.")
    exit()

print(type(imgs))   # <class 'numpy.ndarray'>
print(imgs.shape)   # (height, width, channels) e.g., (480, 640, 3)
print(imgs)         # Prints the pixel values (large array)


<class 'numpy.ndarray'>
(1000, 1500, 3)
[[[112 131 174]
  [111 130 173]
  [111 130 173]
  ...
  [ 48  62  84]
  [ 49  63  85]
  [ 50  64  86]]

 [[110 129 172]
  [111 130 173]
  [111 130 173]
  ...
  [ 48  62  84]
  [ 50  64  86]
  [ 50  64  86]]

 [[110 129 172]
  [111 130 173]
  [110 129 172]
  ...
  [ 46  61  80]
  [ 47  62  81]
  [ 48  63  82]]

 ...

 [[ 78 104 141]
  [ 78 104 141]
  [ 77 103 140]
  ...
  [ 13  39  79]
  [ 12  38  78]
  [ 12  38  78]]

 [[ 80 103 141]
  [ 79 102 140]
  [ 79 102 140]
  ...
  [ 12  37  79]
  [ 12  37  79]
  [ 11  36  78]]

 [[ 79 102 140]
  [ 78 101 139]
  [ 78 101 139]
  ...
  [ 13  38  80]
  [ 13  38  80]
  [ 13  38  80]]]


In [7]:
import cv2

# 1. READ the image
imgs = cv2.imread('UCA-7.jpg')

# 2. Check if image loaded properly
if imgs is None:
    print("❌ Image not found! Please check the file path.")
    exit()
else:
    print(f"✅ Image loaded successfully!")
    print(f"📐 Dimensions: {imgs.shape}")
    print(f"📊 Data type: {imgs.dtype}")
    print(f"🔢 Pixel values (first 10 pixels): {imgs[0][:10]}")

# 3. DISPLAY the image
cv2.imshow('UCA-7.jpg', imgs)

# 4. Wait for any key press
cv2.waitKey(0)

# 5. Clean up
cv2.destroyAllWindows()

✅ Image loaded successfully!
📐 Dimensions: (1000, 1500, 3)
📊 Data type: uint8
🔢 Pixel values (first 10 pixels): [[112 131 174]
 [111 130 173]
 [111 130 173]
 [112 131 174]
 [114 133 176]
 [112 131 174]
 [108 127 170]
 [103 122 165]
 [108 127 170]
 [107 126 169]]


error: OpenCV(4.13.0) D:\a\opencv-python\opencv-python\opencv\modules\highgui\src\window.cpp:1301: error: (-2:Unspecified error) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Cocoa support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function 'cvShowImage'
